Creating a release plan addmission object
konflux-ci/docs pull request #16
Opened 2024-05-08 10:59 UTC by gtrivedi88

**Purpose**: The purpose of this PR is to develop the releasing an application content. I have copied the AppStudio content directly. We have to review and update it.

**Aligned team**: Konflux release team

**Content for preview**: 

**SME review**: 

**QE review**: 

**Peer review**:

2024-05-13 14:49 UTC, arewm approved these changes

2024-05-13 14:49 UTC, arewm commented on docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan-admission.adoc
> +. On the Trusted Application Pipeline console, select the *Release services* > *Release plan admission* tab.
```suggestion
. On the Konflux console, select the *Release services* > *Release plan admission* tab.
```

2024-05-13 14:50 UTC, arewm requested changes
I meant to request changes, not approve. :)

2024-06-03 04:48 UTC, gtrivedi88 commented
Since we will be having a separate release doc. Closing this PR.

2024-06-03 04:48 UTC, closed without merging