Adding SLSA conformity
konflux-ci/docs pull request #22
Opened 2024-05-09 21:58 UTC by missmesss

Copying the SLSA conformity doc published for AppStudio.
The only update is the xref.

2024-05-09 22:02 UTC, missmesss commented
@ralphbean Will you please confirm this doc is good to go for Konflux? The only change is an xref.

A comment from Andrew: I don't see anything apparent off hand other than the links. It is all still pretty generic and SLSA hasn't changed much since it was written either.

Thanks!

2024-05-13 14:45 UTC, arewm requested changes

2024-05-13 14:45 UTC, arewm commented on docs/modules/ROOT/pages/discover/slsa-conformity.adoc
> +SLSA assigns two primary responsibilities to build platforms like {ProductName}:
```suggestion
The SLSA Build (v1.0) specification assigns two primary responsibilities to build platforms like {ProductName}:
```
The specification may change, so we can specifically indicate which track/version we are referencing: https://slsa.dev/spec-stages#versioning

This is also consistent with the additional links at the bottom.

2024-05-13 17:22 UTC, missmesss commented
Thank you for a review @arewm , I've added the spec version as you've suggested.

2024-05-13 17:23 UTC, arewm approved these changes

2024-05-13 18:17 UTC, merged